version: '3'
volumes:
  data-volume: {}
services:
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: sample_mysql_db
    volumes:
      - data-volume:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672