version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-streams-multibinder
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-multibinder-1
    ports:
    - 5672:5672
    - 15672:15672
