spring:
  cloud:
    stream:
      bindings:
        output:
          contentType: application/*+avro
          destination: sensor-topic
      schema-registry-client:
        endpoint: http://localhost:8990
      schema:
        avro:
          schema-locations: classpath:avro/sensor.avsc
server.port: 9009