spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample_mysql_db
    username: root
    password: pwd
    driver-class-name: org.mariadb.jdbc.Driver
jdbc:
  query: select id, name, tag from test order by id
  triggerDelay: 5
spring.cloud.stream.bindings.output.destination: test-data
spring.cloud.stream.bindings.input.destination: test-data

#always use partition 0, but using a complex SpeL below to test the fix for this issue:
#https://github.com/spring-cloud/spring-cloud-stream/issues/1297
spring.cloud.stream.default.producer.partitionkeyexpression: "payload != null ? 0 : 1"