spring:
  cloud:
    stream:
      bindings:
        output:
          destination: partitioned.destination
          producer:
            #payload string length - 1 is the partition where it will get stored
            partition-key-expression: headers['partitionKey'] - 1
            partition-count: 4
            required-groups: myGroup #only applicable for rabbit
