spring:
  cloud:
    stream:
      bindings:
        output:
          destination: average
        test-sink:
          destination: average
        input:
          destination: sensor
        test-source:
          destination: sensor
